server:
  port: '8080'
spring:
  datasource:
    username: sa
    url: jdbc:h2:file:c:/java/adalet3
    driverClassName: org.h2.Driver
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        '[format_sql]': 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: none
